### ISSUE TITLE
Fails to connect when there is a pre sign-in agreement 

### ISSUE THREAD

**Issue by macthecadillac** [russdill/juniper-vpn-py#19]
I was trying to connect to my school vpn but my school vpn has a page that loads that makes you agree to the usage agreement before the actual sign-in page loads. I tried connecting following instructions exactly but it raises an error. Here is the traceback:

Password:
Traceback (most recent call last):
  File "./juniper-vpn.py", line 357, in <module>
    jvpn.run()
  File "./juniper-vpn.py", line 165, in run
    self.action_login()
  File "./juniper-vpn.py", line 213, in action_login
    self.br.form['username'] = self.args.username
  File "/usr/lib/python2.7/dist-packages/mechanize/_form.py", line 2780, in __setitem__
    control = self.find_control(name)
  File "/usr/lib/python2.7/dist-packages/mechanize/_form.py", line 3101, in find_control
    return self._find_control(name, type, kind, id, label, predicate, nr)
  File "/usr/lib/python2.7/dist-packages/mechanize/_form.py", line 3185, in _find_control
    raise ControlNotFoundError("no control matching "+description)
mechanize._form.ControlNotFoundError: no control matching name 'username'
Terminated

If there's anything else that needs to be provided for the issue to be resolved, I'd be happy to help. Thanks.

**Comment by animetrics** [comment]
This is a problem for me as well.  Any work around?

**Comment by animetrics** [comment]
oh, I see that there is a pull request that may resolve this?

**Comment by rbeede** [comment]
I have modified a copy of the code to fix the problem.   Their is a cookie missing DSSigninNotif=1 that signals to go past the screen.  Annoying too is the html form still says frmLogin which confuses the tool.

I will try to post the fix today as a pull request.

**Comment by rbeede** [comment]
Nevermind, this pull request is better.

https://github.com/russdill/juniper-vpn-py/pull/17/files
